/* Auto-generated by utensor cli */
#ifndef __MY_MODEL_INTERFACE_H
#define __MY_MODEL_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class MyModel : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  MyModel();
 protected:
  virtual void compute();
 private:
  // Operators
  ReferenceOperators::Conv2dOperator<int8_t> op_Conv2dOperator_000;

  TflmSymQuantOps::QuantizeOperator<int8_t, float> op_QuantizeOperator_001;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_002;

  TflmSymQuantOps::DequantizeOperator<float, int8_t> op_DequantizeOperator_003;

  ReferenceOperators::ReshapeOperator<int8_t> op_ReshapeOperator_004;

  ReferenceOperators::ReLUOperator<int8_t> op_ReLUOperator_005;

  ReferenceOperators::MaxPoolOperator<int8_t> op_MaxPoolOperator_006;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_007;

  // memory allocators
  localCircularArenaAllocator<5304, uint16_t> ram_allocator;
  localCircularArenaAllocator<1024, uint16_t> metadata_allocator;
};

#endif // __MY_MODEL_INTERFACE_H